Allow format issue output text within individual sections and in general
spring-io/github-changelog-generator pull request #103
Opened 2024-03-05 21:45 UTC by Dinozavvvr

Hi everyone! Here is a simple solution for issue [#47](https://github.com/spring-io/github-changelog-generator/issues/47)

- Allow format issue output text within individual sections and in general
- Removed generateLinks flag

2024-03-06 07:15 UTC, wilkinsona commented
> Removed generateLinks flag

Even if a custom format allows the links to be omitted, having a flag that controls the behavior when using the default format is a useful convenience that I think should be kept.

2024-03-06 07:51 UTC, Dinozavvvr commented
@wilkinsona Could you describe the scenario of how `format` should work in the case where it has `${number}` but the `generateLinks` flag is set to false. I suggest another way to eliminate these conflicts by setting the `default-format` parameter to `${title}`, which is equivalent to `generateLinks=true`.

Another option would be to use `generateLinks=true` to internally set the default format to `${title}`, but not allow `generateLinks` and `default-format` to be set at the same time.

Thank you for your feedback, please say me if you have any other ideas

2024-03-06 08:07 UTC, wilkinsona commented
I would only apply `generateLinks` to the default format and ignore it when a custom format has been supplied.

When using a custom format, I don't think `${number}` should generate a link. It should only output the issue's number. If you want a link, I would expect the format to be something like `${title} [${number}](${url})`. This should provide complete control over the link and its text. You could then also do something like `[${title} ${number}](${url})` if you want the issue's title to be part of the link text.

2024-03-11 16:01 UTC, Dinozavvvr commented
Hi again @wilkinsona. I've put `generate-links` back the way it worked before. Now, if `default-format` is explicitly specified, the `generate-links` flag is ignored. If `default-format` is not specified, `generate-links` then `"${title}"` will be used as the default format, as it worked before. Is it what you wanted?

2024-03-26 04:39 UTC, Dinozavvvr commented
Hi everyone! So what is with this pull request?

2024-03-26 07:29 UTC, snicoll commented
@Dinozavvvr nothing except the team is very busy and has other priorities right now.

2024-06-13 10:59 UTC, wilkinsona requested changes

2024-06-13 10:59 UTC, wilkinsona commented on src/main/java/io/spring/githubchangeloggenerator/ApplicationProperties.java
> +import io.spring.githubchangeloggenerator.github.service.Repository;
Please don't re-order the imports. It adds noise to the diff, making the changes harder to review. If you run `./gradlew build`, you will see failures from both Checkstyle and Spring Java Format that should be corrected please.

2024-06-13 10:59 UTC, wilkinsona commented on src/main/java/io/spring/githubchangeloggenerator/ApplicationProperties.java
> +
This looks like a whitespace-only change. Please revert.

2024-06-13 10:59 UTC, wilkinsona commented on src/main/java/io/spring/githubchangeloggenerator/ApplicationProperties.java
> +		private final boolean generateLinks;
Why do we need a second property for this? The `Issues` inner-class already has one.

2024-06-13 10:59 UTC, wilkinsona commented on src/main/java/io/spring/githubchangeloggenerator/ApplicationProperties.java
> +				@DefaultValue("true") Boolean generateLinks, String defaultFormat) {
Why has `generatedLinks` been changed from `boolean` to `Boolean`?

2024-06-13 10:59 UTC, wilkinsona commented on src/main/java/io/spring/githubchangeloggenerator/ChangelogGenerator.java
> +import io.spring.githubchangeloggenerator.github.service.Repository;
Please correct the imports as per the problems reported by Checkstyle when you run `./gradlew build`.

2024-06-13 10:59 UTC, wilkinsona commented on src/main/java/io/spring/githubchangeloggenerator/ChangelogGenerator.java
> +            content.append((!content.isEmpty()) ? String.format("%n") : "");
Switching to `isEmpty()` is unrelated to allowing more control over the formatting. Please revert.

2025-01-18 22:50 UTC, wilkinsona commented
Closing due to inactivity.

2025-01-18 22:50 UTC, closed without merging